# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
    - libgmp-dev

# The different configurations we want to test. You could also do things like
# change flags or use --stack-yaml to point to a different file.
env:
- ARGS=""
#- ARGS="--resolver=nightly"
- ARGS="--stack-yaml=stack-8.2.2.yaml"
- ARGS="--stack-yaml=stack-8.0.2.yaml"
- ARGS="--stack-yaml=stack-8.0.1.yaml"
- ARGS="--stack-yaml=stack-7.10.3.yaml"
- ARGS="--stack-yaml=stack-7.8.4.yaml"


before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

# This does all of the work: installs GHC if necessary, builds the
# library, executables, and test suites, and runs the test suites.
# `--no-terminal works` around some quirks in Travis's terminal implementation.
script: 
- stack $ARGS --no-terminal --install-ghc build
- stack $ARGS --no-terminal test
#- stack $ARGS --no-terminal --install-ghc bench

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

notifications:
  email:
    - suhailshergill@gmail.com
  on_success: change
  on_failure: always
